/*
 * Decompiled with CFR 0.137.
 */
package im.prefs;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.math.BigInteger;
import java.util.Properties;

public class Preferences {
    File prefFile;
    Properties prefs;

    public Preferences(File file) {
        block3 : {
            this.prefFile = file;
            this.prefs = new Properties();
            try {
                if (this.prefFile.exists()) {
                    this.prefs.load(new FileInputStream(this.prefFile));
                    break block3;
                }
                this.prefFile.createNewFile();
            }
            catch (Exception exception) {
                exception.printStackTrace();
            }
        }
    }

    public void savePreferences() {
        try {
            this.prefs.store(new FileOutputStream(this.prefFile), "programatically generated by P2PIM");
        }
        catch (Exception exception) {
            exception.printStackTrace();
        }
    }

    public static File findPrefsDirectory() {
        String string = System.getProperty("user.home");
        string = string.concat("/.p2pim");
        File file = new File(string);
        file.mkdir();
        return file;
    }

    public BigInteger getUserID() {
        String string = null;
        string = this.prefs.getProperty("UserID");
        if (string == null) {
            return null;
        }
        BigInteger bigInteger = new BigInteger(string);
        return bigInteger;
    }

    public void setUserID(BigInteger bigInteger) {
        this.prefs.setProperty("UserID", bigInteger.toString());
        this.savePreferences();
    }

    public void setAutoLogin(boolean bl) {
        this.prefs.setProperty("auto.login", new Boolean(bl).toString());
        this.savePreferences();
    }

    public String getAutoLogin() {
        return this.prefs.getProperty("auto.login");
    }

    public void setMostRecentUsername(String string) {
        this.prefs.setProperty("username.recent", string);
        this.savePreferences();
    }

    public String getMostRecentUsername() {
        return this.prefs.getProperty("username.recent");
    }

    public void setUsernameHistory(String string, int n) {
        String string2 = "username.history." + n;
        this.prefs.setProperty(string2, string);
        this.savePreferences();
    }

    public String getUsernameHistory(int n) {
        String string = "username.history." + n;
        return this.prefs.getProperty(string);
    }

    public String getProfile() {
        return this.prefs.getProperty("UserProfile");
    }

    public void setProfile(String string) {
        this.prefs.setProperty("UserProfile", string);
        this.savePreferences();
    }
}

